WScript.Sleep 1000
Set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.Run "notepad"
WScript.Sleep 100
WshShell.AppActivate "Notepad"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
WshShell.SendKeys "Error"
WScript.Sleep 500
